version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - client.env
    ports:
      - 3040:3040
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/usr/src/app/src

  # api:
  #   ports:
  #     - 3030:3030
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev
  #   volumes:
  #     - ./api/src:/usr/src/app/src

  # api_db:
  #   ports:
  #     - 27017:27017

  # nginx:
  #   volumes:
  #     - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
